dist: bionic

language: python

python: 3.7

services:
  - docker

branches:
  only:
    - master
    - /^v.*$/

jobs:
  include:

    - stage: Run tests
      name: Docker-compose with PostGIS database
      install:
        - cd .docker
        - ./start.sh
      script:
        - ./exec.sh

    - stage: Push translations to Transifex
      if: branch = master
      install:
        - pip3 install git+https://github.com/Gustry/qgis-plugin-ci.git
      script: qgis-plugin-ci push-translation ${TX_TOKEN}

    - stage: Deploy
      if: tag IS present
      name: Create release
      install:
        - pip3 install git+https://github.com/Gustry/qgis-plugin-ci.git
      before_deploy:
        - export RELEASE_TITLE="Release of $TRAVIS_TAG"
      script:
        - qgis-plugin-ci -v
      deploy:
        - provider: releases
          edge: true
          file: .
          name: ${RELEASE_TITLE}
          api_key: ${GH_TOKEN}
          on:
            tags: true

        - provider: script
          script: qgis-plugin-ci release ${TRAVIS_TAG} --github-token ${GH_TOKEN} --transifex-token ${TK_TOKEN} --create-plugin-repo --allow-uncommitted-changes
          on:
            tags: true

        - provider: script
          skip_cleanup: true
          script: ./github/push_translations_to_github.sh
          on:
            tags: true
